name: CI-CD

on:
  push:
    branches: 
    - tests/unit

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js 20.16
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm i
    - name: Run Build
      run: npm run build
